### ISSUE TITLE
Create talent mongoose model

### ISSUE THREAD

**Issue by Ayobami6** [Ayobami6/MeetDevs#2]

**Comment by betiniakarandut** [comment]
Okay. How do we go about it?

**Comment by betiniakarandut** [comment]
Okay. How do we go about it?
We can look into it today probably

**Comment by Ayobami6** [comment]
Yes, we need to connect to the mongodb database using mongoose js library

**Comment by jojothomas1515** [comment]
on this

**Comment by Ayobami6** [comment]
Alright
Please make sure you pull from staging branch
