### ISSUE TITLE
Implement Talent SignIn and SignUp logic

### ISSUE THREAD

**Issue by Utilitycoder** [Ayobami6/MeetDevs#38]
Implement signup and SignIn logic for talent as the first instance of talking to the server from the client.

**Comment by Ayobami6** [comment]
Bro, this has been implemented

**Comment by Ayobami6** [comment]
There's the employer ApI crud endpoint. that has not been assigned
which are;
get an employer
update an employer
and delete an employer

**Comment by Utilitycoder** [comment]
Really? I have seen the sign up page but I am not sure I understand the approach you want to take. I am thinking of fetching -> storing into state in client -> and then rendering the result.

**Comment by Ayobami6** [comment]
You mean when the request for signup is being sent, we should have the response stored into a state right?
And, if thats right, thats basically what the implemented approach took mostly, just that the response wasn't directly stored to a state but instead to the app local storage, so we can easily update a state with this by getting the data from the storage.
