### ISSUE TITLE
create talent single card components for the employer page

### ISSUE THREAD

**Issue by Ayobami6** [Ayobami6/MeetDevs#50]

**Comment by Utilitycoder** [comment]
So this card component will display profiles of available talents that match an employer's requirement and will be displayed on their dashboard?

**Comment by Ayobami6** [comment]
Yeah, the card is a mini talent profile card that every employers to the when they login to their page, it's where we will render the necessary data of all talent from the database

**Comment by Ayobami6** [comment]
Check the Airbnb page, something like that they have for their homes
